#easy_admin:
#  site_name: 'Mano ir tik Mano'
#
#  user:
#    display_name: true
#    display_avatar: true
#    name_property_path: 'fullName'
#
#  entities:
#    - App\Entity\Contact
#    - App\Entity\User